### ISSUE TITLE
Compactible With PCA8574?

### ISSUE THREAD

**Issue by mohdrais** [mathertel/LiquidCrystal_PCF8574#11]
I have tested with Arduino Nano Every with I2CLCD 16x2 and  I2CLCD 20x4 with PCA8574 I2C expander. Both failed.

**Comment by jasonmarkham** [comment]
I tested it with pcf8574AT - it failed to show characters - only gibberish on lcd

**Comment by mathertel** [comment]
Please let me know what adapter board you are using.

Please see the article at http://mathertel.de/Arduino/LiquidCrystal_PCF8574.aspx.
The wiring may differ when using other chips or boards.
The common board i use is using the 8 bits the following way:

Bit | Signal
-- | --
1 | PCF_RS
2 | PCF_RW
3 | PCF_EN
4| PCF_BACKLIGHT
5..8 | 4 bits of data
