### ISSUE TITLE
optimising _sendNibble to write faster (about 3 time less I2C send for the same job)

### ISSUE THREAD

**Issue by net234** [mathertel/LiquidCrystal_PCF8574#12]
Hello 
I propose a small modification to the   so I2C is open and close 4 time less and so you can write faster to LCD device

I am new to github and arduino (but i have 20 years of ASM programing and hardware on lot of processor but classical way :) )
I give you the modifications but may be I should make a clone ?   (this is not clear for me)

[LiquidCrystal_PCF8574.zip](https://github.com/mathertel/LiquidCrystal_PCF8574/files/4624474/LiquidCrystal_PCF8574.zip)

**Comment by mathertel** [comment]
Please make a clone and create a pull request so we can see the changes here.

**Comment by net234** [comment]
I have made a clone and updated the files
I tried a Pull of the repository but i don't see anything ...
Should I made a fork on my side ?
