### ISSUE TITLE
no matching function for call to 'LiquidCrystal_PCF8574::createChar(int, byte [8])'

### ISSUE THREAD

**Issue by jasonmarkham** [mathertel/LiquidCrystal_PCF8574#17]
I defined the character as a byte 
byte cM[8] = {B01100, B10000, B10000, B01100, B10001, B01010, B00100, B00100};

initialise in setup with 
lcd.createChar(0, cM);

When I compile I get this error 

no matching function for call to 'LiquidCrystal_PCF8574::createChar(int, byte [8])'

**Comment by mathertel** [comment]
The createChar() function in the latest published version had the problem to use a int[8] instead of a byte[8] parameter.
In the current master this has been fixed already.
Will be fixed in the next version. You can use the master from github, change the array to int[8] for now..

**Comment by mathertel** [comment]
Next version is 2.0.0 and has this interface change as requested.
A PROGMEM version will be available vor AVR processors as well #22
