### ISSUE TITLE
LCD show ramdom caracteres after a while

### ISSUE THREAD

**Issue by carlosprato1** [mathertel/LiquidCrystal_PCF8574#19]
hello very good library. i am new to arduino but

I would like to know if there is any reason why the LCD screen shows random characters after a while.

eg bad settings ?, noise ?, is it a common feature on LCD? does the library have any functions that allow me to take control of the lcd again?

Thank you.

**Comment by tiny-eng** [comment]
hi
i have same problem in esp32

**Comment by carlosprato1** [comment]
@tiny-eng  solved it by calling lcd.begin () periodically in the loop, for me it was enough to call it once every 20 seconds.

**Comment by tiny-eng** [comment]
hi.
thank you very much
I did have a problem with pin soldering.
Are you sure about soldering pins?

**Comment by carlosprato1** [comment]
@tiny-eng I'm glad you fixed the problem.

In my case I had the pins well soldered and the LCD seemed stable, but as time passed (between 20 min to approximately 1 hour) I lost control of the LCD and it showed random characters (it also happened if an electric motor was activated nearby).
so I decided to use the lcd.begin() periodically to get the LCD back.

It may also be that the LCD or LCD driver that I use is of poor quality (I bought them through aliExpress)

but I don't know exactly.
