### ISSUE TITLE
Change the bit allocations?

### ISSUE THREAD

**Issue by denysparnell** [mathertel/LiquidCrystal_PCF8574#2]

**Comment by denysparnell** [comment]
Hi.

As Arduino has been updated, it continues to break the old libraries I've used so I want to move to some that get loaded with the inbuilt library manager. But, not being a good programmer, I don't know what you mean by "If you like to adjust this to an adapter board with a different wiring you can do this in the internal function _write2Wire." on your web page.

Another library used in the past has...

//LiquidCrystal_I2C lcd(0x20);  // Set the LCD I2C address
//                    addr, en,rw,rs,d4,d5,d6,d7,bl,blpol
LiquidCrystal_I2C lcd(0x20, 4, 5, 6, 0, 1, 2, 3, 7, NEGATIVE);  // Set the LCD I2C address

As Arduino has been updated, it continues to break the old libraries I've used so I want to move to some that get loaded with the inbuilt library manager. But, not being a good programmer, I don't know what you mean by "If you like to adjust this to an adapter board with a different wiring you can do this in the internal function _write2Wire." on your web page.

I do like that you have named your library something other than the original "LiquidCrystal_LCD" as the replacement one I used before was named the same as the original. More confusion to the masses ;)

**Comment by fixingthingsguy** [comment]
Thanks for creating this library. I tried is successfully * on an LCD with a  backpack marked as "MH" . For the "mjdkz" marked backpack I need to use LiquidCrystal_I2c.h library. The "MH" LCD w/backpack doesn't work (blinks occasionally) when using the LiquidCrystal_I2.h library. I'm wondering what the difference might be and, for fun, I ask, could they be merged into a single library? 
*I can't count the needless hours I spent while this library was available and in sight too!! Using Arduino IDE on a nodemcu esp8266 1.0
Regards,

**Comment by mathertel** [comment]
The wiring of the adapter must match the library coding.
Most adapter boards pass data in the upper 4 bits and use the lower 4 bits for the control lines.

The library mentioned above does this by some complex code.
When us use less code then you can change the
`void LiquidCrystal_PCF8574::_write2Wire()` implementation to the wiring of your library.
