### ISSUE TITLE
Licensing terms

### ISSUE THREAD

**Issue by bperrybap** [mathertel/LiquidCrystal_PCF8574#3]
If the code is a derivative of the Arduino LiquidCrystal code (as indicated by the comments in the code) any license used for this project must be compatible with the LiquidCystal license which is LGPL 2.1+
LGPL 2.1+ licensed code can not be changed to a more permissive license such as BSD or MIT.
It would have to remain LGPL 2.1+

**Comment by mathertel** [comment]
I added notes on the license situation:
See commit: https://github.com/mathertel/LiquidCrystal_PCF8574/commit/9236b861ae7b68062f71741c91bca5936689c30e
